from enum import StrEnum


class SohposStrings(StrEnum):
    SOHPOS_URI_PROJECT = "https://github.com/thetrotfreak/sohpos"
    SOHPOS_URI_PROJECT_TOOLTIP = "View on GitHub"
    SOHPOS_URI_LICENSE = "https://github.com/thetrotfreak/sohpos/blob/main/LICENSE"
    SOHPOS_URI_LICENSE_TOOLTIP = "View License"
    SOHPOS_URI_ISSUES = "https://github.com/thetrotfreak/sohpos/issues"
    SOHPOS_URI_ISSUES_TOOLTIP = "Found a bug? Report here"
    SOHPOS_URI_WIKI = "https://github.com/thetrotfreak/sohpos/wiki"
    SOHPOS_URI_WIKI_TOOLTIP = "Read the Wiki"
    SOHPOS_AUTHOR = "thetrotfreak"
    SOHPOS_VERSION = "v0.9.0"
    SOHPOS_COMMIT = ""
    SOHPOS_COPYRIGHT = "Copyright (c) 2024 Bivas Kumar"
    SOHPOS_LICENSE = "MIT License"
    SOHPOS_APP_NAME = "Sohpos"
    SOHPOS_APP_DESCRIPTION = "Internet Access Portal"
    SOHPOS_LOGIN_STATUS = "Connected"
    SOHPOS_LOGOUT_STATUS = "Disconnected"
    SOHPOS_ENDPOINT = "http://192.168.100.100:8090/httpclient.html"
    # SOHPOS_ENDPOINT = "http://127.0.0.1:8080"
    SOHPOS_VALIDATION_USERNAME = "*username required"
    SOHPOS_VALIDATION_PASSWORD = "*password required"
    SOHPOS_SIGN_IN = "sign in"
    SOHPOS_SIGN_OUT = "sign out"
    SOHPOS_GENERIC_BASE_ERROR = "Oops! Something went wrong."
    SOHPOS_GENERIC_VALIDATION_ERROR = "Oops! Perhaps your credentials are incorrect."
    SOHPOS_DIALOG_THEME_MODE = "choose your mode"
    SOHPOS_DIALOG_THEME = "choose your theme"
